<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="HD1AB2KY78F1DTO" name="Test(failed)(failed)" tests="1" failures="1" timestamp="9 Sep 2018 07:16:32 GMT" time="8.571" errors="0">
  <testcase name="test1" time="2.609" classname="SeleniumTest.com.delta.test.Test1">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
	at SeleniumTest.com.delta.test.Test1.test1(Test1.java:25)
	at SeleniumTest.com.delta.test.TakeScreenshotListener.onFinish(TakeScreenshotListener.java:41)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- test1 -->
</testsuite> <!-- Test(failed)(failed) -->
